task: detection

num_classes: 80
remap_mscoco_category: True

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home/zecoy/datasets/FLIR/RGB/train/
    ann_file: /home/zecoy/datasets/FLIR/RGB/annotations/train.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 1
  num_workers: 0
  drop_last: True


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home/zecoy/datasets/FLIR/RGB/val/
    ann_file: /home/zecoy/datasets/FLIR/RGB/annotations/val.json
    transforms:
      type: Compose
      ops: ~

  shuffle: False
  batch_size: 1
  num_workers: 0
  drop_last: False
